namespace VPC.Framework.Business.DynamicQueryManager.Contracts
{
    public static class BusinessConstant
    {
        public const string TenantId = "[TenantId]";
        public const string UpdatedBy = "[UpdatedBy]";
        public const string UpdatedDate = "[UpdatedOn]";
        public const string EntityCode = "[EntityCode]";
        public const string EntitySubtype = "[EntitySubTypeCode]";

        public const string AutogeneratedCode = "[Code]";


        public const string PasswordReplace = "Password";
        public const string PasswordHash = "[PasswordHash]";
        public const string PasswordSalt = "[PasswordSalt]";
 public const string Name = "[Name]";
        
        public const bool IsPickList = false;
 public const string Active = "[Active]";
    }
}